---
- name: Install Jenkins on Ubuntu 20.04 with JCasC
  hosts: your_ubuntu_server
  become: true

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Add Jenkins repository key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Wait for Jenkins to start
      wait_for:
        port: 8080
        timeout: 60

    - name: Get Jenkins initial admin password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_admin_password

    - name: Print Jenkins admin password
      debug:
        var: jenkins_admin_password.stdout_lines

    - name: Install Jenkins plugins
      include_vars:
        file: plugin.yaml
        name: plugins
      loop: "{{ plugins }}"
      include_tasks: install_jenkins_plugin.yaml
      loop_control:
        loop_var: plugin

    - name: Copy JCasC YAML file
      copy:
        src: jenkins.yaml
        dest: /var/lib/jenkins/jenkins.yaml
      notify: Restart Jenkins

  handlers:
    - name: Restart Jenkins
      service:
        name: jenkins
        state: restarted
